# Generated by Django 4.2.11 on 2024-03-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_gerenciador", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do material"),
                ),
                (
                    "unidade_medida",
                    models.CharField(max_length=15, verbose_name="Unidade de medida"),
                ),
            ],
            options={"verbose_name_plural": "Materiais",},
        ),
        migrations.AlterModelOptions(
            name="projeto", options={"verbose_name_plural": "Projetos"},
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="dt_criacao",
            field=models.DateField(verbose_name="Data de criação"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome do projeto"),
        ),
        migrations.AddField(
            model_name="projeto",
            name="lista_de_materiais",
            field=models.ManyToManyField(
                to="app_gerenciador.material", verbose_name="Lista de materiais"
            ),
        ),
    ]
