# Generated by Django 4.2.11 on 2024-04-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador', '0002_material_alter_projeto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do serviço')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dt_inicio', models.DateField(verbose_name='Data de inicio')),
                ('dt_entrega', models.DateField(verbose_name='Data de entrega')),
            ],
            options={
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
