# Generated by Django 4.2.11 on 2024-04-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador', '0003_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='dt_entrega',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='dt_inicio',
        ),
        migrations.AddField(
            model_name='servico',
            name='codigo',
            field=models.CharField(max_length=100, null=True, verbose_name='Codigo do serviço'),
        ),
        migrations.AddField(
            model_name='servico',
            name='quantidade',
            field=models.CharField(max_length=15, null=True, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='servico',
            name='unidade_medida',
            field=models.CharField(max_length=15, null=True, verbose_name='Unidade de medida'),
        ),
    ]
