# Generated by Django 4.2.11 on 2024-04-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador', '0004_remove_servico_dt_entrega_remove_servico_dt_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='lista_de_servicos',
            field=models.ManyToManyField(to='app_gerenciador.servico', verbose_name='Lista de serviços'),
        ),
    ]
