# Generated by Django 4.2.11 on 2024-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador', '0005_projeto_lista_de_servicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='lista_de_servicos',
            field=models.ManyToManyField(to='app_gerenciador.servico', verbose_name='Lista de codigo de serviços'),
        ),
    ]
